theme: jekyll-theme-cayman

# Navigation (Optional)
title: "Statistics with R"
description: "Fundamentals of Statistics with R."

kramdown:
  math_engine: mathjax

# Enable navigation links
include:
  - chapters/